# @package _global_

defaults:
  - mlp_optuna  # Inherit from base config
  - _self_      # Allow this file to override

# Override the optimized metric
optimized_metric: "val/r2"

# WandB tags
tags: ["flexmoe", "hparam_search", "kcat", "regression", "e2e_a100_2"]

model:
  task_type: regression
  value_types:
    - kcat
  num_experts: 127
  num_routers: 1

data:
  batch_size: 128
  num_workers: 32
  pin_memory: true
  persistent_workers: true
  warmup_epochs: 5

  data_dir: ${paths.kinetic_dataset_path}
  _split_dir: "substrate_splits"
  _difficulty: "hard"

trainer:
  max_epochs: 50

# Override study name
hydra:
  sweeper:
    study_name: FlexMoE
    n_jobs: 1
    direction: maximize
    n_trials: 50

# Override or add new search params
    params:
      model.hidden_dim: choice(256, 512, 1024)
      model.num_layers: choice(2, 3, 4)
      model.num_layers_mlp_pred: choice(2, 3)
      model.top_k: choice(1, 2, 3, 4)
      model.num_heads: choice(1, 2, 4, 8)
      model.dropout: choice(0.1, 0.15, 0.2)
      optimizer.lr: choice(1e-3, 5e-4, 1e-4)